### PR TITLE
Peru JS automation

### PR DESCRIPTION
**Pull request by anna-s-ocean**
## Task 
- create dataProvider.js, HTML translators, and display list files and function for all three types of list
- updated import locations to match directory pathway 

## Check
- does the content show up for each three list

### CODE REVIEW

**Comment by rickiele** [comment]
Make sure to have the latest main with Iman's New Zealand scripts. Everything else looks good.

**Comment by tcurtis97** [comment]
👍

**Comment by anna-s-ocean** [comment]
updated to include New Zealand!

**Comment by rickiele** [comment]
Sweet! 👍

**Pull request merged**
