### PR TITLE
add scotland

### PR DESCRIPTION
**Pull request by rickiele**
### Changes Made

- filled in Scotland information, added Scotland link

### Check The Following

- check for new Scotland information, see if the picture shows

### CODE REVIEW

**Comment by TKomrij** [comment]
👍🏻

**Comment by imannadeem825** [comment]
looks great, love that picture!

**Comment by anna-s-ocean** [comment]
👍

**Comment by tcurtis97** [comment]
👍

**Comment by TKomrij** [comment]
👍🏻

**Pull request merged**
