### PR TITLE
Amm peru

### PR DESCRIPTION
**Pull request by anna-s-ocean**
## Task completed
1) all required text
2) added country picture with dimensions of 1000 by 300
3) changed nav links to country names

## Check 
1) nav links name
2) picture

### CODE REVIEW

**Comment by TKomrij** [comment]
👍🏻

**Comment by rickiele** [comment]
👍

**Comment by imannadeem825** [comment]
looking good!

**Comment by rickiele** [comment]
👍

**Comment by tcurtis97** [comment]
👍

**Pull request merged**
