### PR TITLE
changed backgroundand text color

### PR DESCRIPTION
**Pull request by tcurtis97**
## Test
1) test to make sure each page has a text change to indigo
2)test each page to make sure each page has the new background

### CODE REVIEW

**Comment by imannadeem825** [comment]
Looks good, not sure if we wanted to keep in the same font family as what Rickie was using though?

**Comment by rickiele** [comment]
Maybe replace the nav font in the **_main.css_** for consistency to: 
font-family: 'Poppins', sans-serif;

Everything else looks good though!

**Comment by TKomrij** [comment]
In styles you accidentally created an empty file called background.

**Comment by anna-s-ocean** [comment]
👍

**Pull request closed without merging**
